Detect intermediate input changes with a better event -> the input event
wesbos/JavaScript30 pull request #388
Opened 2020-09-12 20:12 UTC by csaltos

NOTE: at newer version of Firefox, Chrome and Edge, the mousemove event do not cover intermediate changes on the color input … but this commit with the new input event works fine, maybe a simple suggestion on how to improve that. Thank you for your cool course, it’s really good and helpful.

2020-09-29 07:02 UTC, SurajJadhav7 commented
@csaltos I spent an hour wondering why "mouseover" and "change" wasn't working in chrome (85.0.4183.102). Thanks for solution PR.

2020-10-06 13:45 UTC, uzair004 commented
hey, little off topic, but can you tell me how to have similar repo structure. I want to have a repo which is collection of particular codes/directory each having its own .git file for tracking changes ?

2021-06-18 01:09 UTC, bmrejen requested changes

2021-06-18 01:09 UTC, bmrejen commented on 03 - CSS Variables/index-FINISHED.html
> +    inputs.forEach(input => input.addEventListener('input', handleUpdate));
interesting

2024-06-03 02:01 UTC, closed without merging